package com.mobile_client.utils

import androidx.compose.ui.graphics.Color
import com.mobile_client.screens.R

enum class AppTheme {
    CARROTS,
    AUBERGINES
}

data class ThemeAssets(
    val title: String,
    val button3: Int,
    val button4: Int,
    val backgroundLeaderboardPage: Int,
    val backgroundMainPage: Int,
    val backgroundCreationPage: Int,
    val backgroundWaitingPage: Int,
    val backgroundCharacterPage: Int,
    val backgroundBoxCode: Int,
    val backgroundInventory: Int,
    val footerColor: Color,
    val userListBackgroundColor: Color,
    val userBackgroundColor: Color,
    val backButtonColor: Color,
    val backButtonColorHover: Color,
    val mainPageTextColor: Color,
    val tabIndicatorColor: Color,
    val headerRightBackground: Color,
    val headerRightBorder: Color,
    val buyButtonBackground: Color,
    val equipAlreadyBackground: Color,
    val itemShopBackground: Color,
    val itemInventoryBackground: Color,
    val price: Color,
    val boxAccount: Color,
    val textAccount: Color,
    val buttonOutlineAccount: Color,
    val buttonBackgroundAccount: Color,
    val joinButton: Color,
    val gameListBackground: Color,
    val mapBackground: Color,
    val textMap: Color,
    val characterFormOutline: Color,
    val statsCharacterOutline: Color,
    val characterCreateButton: Color,
    val totalWon: Color,
    val statsBackground: Color,
    val leaderBoardBackground: Color,
    val leaderBoardActive: Color,
    val leaderBoardInactive: Color,
    val leaderBoardRow: Color,
    val leaderBoardHeader: Color,
    val friendsButton: Color,
    val tutorialTrackColor: Color,
    val gameCreationButton: Color,
    val gameCreationButtonText: Color,
    val gameViewBackground: Color,
    val gameViewBackgroundComponent: Color,
    val abandon: Color,
    val endTurn: Color,
    val action: Color,
    val inventoryBox: Color,
    val textActions: Color,
    val playerItem: Color,
    val playerItemActive: Color,
    val playerStats: Color,
    val backgroundAccount: Int,
    val unequip: Color,
    val alreadyUnequipped: Color,
    val tutorialImages: List<Int>
)

val themeAssetsMap = mapOf(
    AppTheme.CARROTS to ThemeAssets(
        title = "Les Carottes",
        button3 = R.drawable.carrot3,
        button4 = R.drawable.carrot4,
        backgroundLeaderboardPage = R.drawable.leaderboard_background,
        backgroundMainPage = R.drawable.main_page,
        backgroundCreationPage = R.drawable.farm,
        backgroundWaitingPage = R.drawable.main_page,
        backgroundCharacterPage = R.drawable.grass_backround,
        backgroundBoxCode = R.drawable.tomato,
        backgroundInventory = R.drawable.inventory,
        footerColor = Color(243, 169, 193),
        userListBackgroundColor = Color(54, 206, 100),
        userBackgroundColor = Color(23, 143, 63),
        backButtonColor = Color(224, 140, 210),
        backButtonColorHover = Color(0xFFD48AB8),
        mainPageTextColor = Color.Black,
        tabIndicatorColor = Color(0xFFFF8C2E),
        headerRightBackground = Color(128, 177, 255, 110),
        headerRightBorder = Color(0, 0, 0, 40),
        buyButtonBackground = Color(76, 175, 80, ),
        equipAlreadyBackground = Color(177, 157, 119),
        itemShopBackground = Color(207, 244, 233),
        itemInventoryBackground = Color(180, 216, 166),
        price = Color(107, 84, 208),
        boxAccount = Color(0, 0, 0, 30),
        textAccount = Color.White,
        buttonOutlineAccount = Color(255, 255, 255, 60),
        buttonBackgroundAccount = Color.Transparent,
        joinButton = Color(27, 136, 17),
        gameListBackground = Color(0x5C302F2F),
        mapBackground = Color(0xFFDDDDDD),
        textMap = Color(0xFF555555),
        characterFormOutline = Color(22,186,85),
        statsCharacterOutline = Color(22,186,85),
        characterCreateButton = Color(19,222,87),
        totalWon = Color(255, 89, 0),
        statsBackground = Color(187, 244, 113),
        leaderBoardBackground = Color(0, 0, 0, 80),
        leaderBoardActive = Color(238, 255, 169),
        leaderBoardInactive = Color(215, 215, 215),
        leaderBoardRow = Color(134, 183, 251, 225),
        leaderBoardHeader = Color(238, 255, 169),
        friendsButton = Color(92, 111, 163),
        tutorialTrackColor = Color(0xFF4CAF50),
        gameCreationButton = Color(101,207,104),
        gameCreationButtonText = Color.White,
        gameViewBackground = Color(113,90,0,35),
        gameViewBackgroundComponent = Color(249,249,249),
        abandon = Color(240,65,65),
        endTurn = Color(76,175,80),
        action = Color(25,118,210),
        inventoryBox = Color.LightGray,
        textActions = Color.White,
        playerItem = Color(243,243,243),
        playerItemActive = Color(232,245,233),
        playerStats = Color.Gray,
        backgroundAccount = R.drawable.account_background,
        unequip = Color.Red,
        alreadyUnequipped = Color(255,147,147),
        tutorialImages = listOf(
            R.drawable.home1,
            R.drawable.home_chat,
            R.drawable.chat,
            R.drawable.home_friends,
            R.drawable.store1,
            R.drawable.inventory1,
            R.drawable.account,
            R.drawable.join1,
            R.drawable.character,
            R.drawable.creation1,
            R.drawable.creation2,
            R.drawable.lobby,
            R.drawable.game1,
            R.drawable.game2,
            R.drawable.endgame,
            R.drawable.leaderboard,
        )
    ),
    AppTheme.AUBERGINES to ThemeAssets(
        title = "Les Aubergines",
        button3 = R.drawable.eggplant3,
        button4 = R.drawable.eggplant4,
        backgroundLeaderboardPage = R.drawable.second_leaderboard_background,
        backgroundMainPage = R.drawable.second_main_page,
        backgroundCreationPage = R.drawable.second_creation_page,
        backgroundWaitingPage = R.drawable.second_main_page,
        backgroundCharacterPage = R.drawable.second_grass_background,
        backgroundBoxCode = R.drawable.mushroom,
        backgroundInventory = R.drawable.second_inventory,
        footerColor = Color(127, 154, 198),
        userListBackgroundColor = Color(255, 255, 255, 90),
        userBackgroundColor = Color.White,
        backButtonColor = Color(113, 181, 207),
        backButtonColorHover = Color(84, 172, 207),
        mainPageTextColor = Color.White,
        tabIndicatorColor = Color(0xFF7B2FBE),
        headerRightBackground = Color(255, 255, 255, 40),
        headerRightBorder = Color(255, 255, 255, 70),
        buyButtonBackground = Color(138, 117, 255),
        equipAlreadyBackground = Color(192, 185, 255),
        itemShopBackground = Color(83, 108, 177),
        itemInventoryBackground = Color(169, 69, 69),
        price = Color(255, 179, 0),
        boxAccount = Color(255, 255, 255, 60),
        textAccount = Color.Black,
        buttonOutlineAccount = Color(0, 0, 0, 60),
        buttonBackgroundAccount = Color(189, 189, 189, 60),
        joinButton = Color(2, 165, 180),
        gameListBackground = Color.White.copy(alpha = 0.3f),
        mapBackground = Color.Black.copy(alpha = 0.75f),
        textMap = Color.White.copy(alpha = 0.92f),
        characterFormOutline = Color(255,36,36),
        statsCharacterOutline = Color(2, 165, 195),
        characterCreateButton = Color(222,19,19),
        totalWon = Color(183, 0, 255),
        statsBackground = Color(0, 167, 151),
        leaderBoardBackground = Color(255, 255, 255, 160),
        leaderBoardActive = Color(49, 0, 183),
        leaderBoardInactive = Color.LightGray,
        leaderBoardRow = Color(255, 255, 255, 80),
        leaderBoardHeader = Color(204, 204, 204, 80),
        friendsButton = Color(119, 66, 175),
        tutorialTrackColor = Color(119, 66, 175),
        gameCreationButton = Color(255, 248, 222),
        gameCreationButtonText = Color(16,32,46),
        gameViewBackground = Color(34,0,113,85),
        gameViewBackgroundComponent = Color(54,53,117),
        abandon = Color(132,82,21),
        endTurn = Color(126,28,255),
        action = Color(169,150,0),
        inventoryBox = Color(182,155,165),
        textActions = Color(255,246,71),
        playerItem = Color(179,201,255),
        playerItemActive = Color(209,255,245),
        playerStats = Color.Black,
        backgroundAccount = R.drawable.second_account_background,
        unequip = Color(0,149,255),
        alreadyUnequipped = Color(127,154,177),
        tutorialImages = listOf(
            R.drawable.dark_home1,
            R.drawable.dark_home_chat,
            R.drawable.chat,
            R.drawable.dark_home_friends,
            R.drawable.dark_store,
            R.drawable.dark_inventory,
            R.drawable.dark_account,
            R.drawable.dark_join1,
            R.drawable.dark_character,
            R.drawable.dark_creation1,
            R.drawable.dark_creation2,
            R.drawable.dark_lobby,
            R.drawable.dark_game1,
            R.drawable.dark_game2,
            R.drawable.dark_endgame,
            R.drawable.dark_leaderboard,
        )
    ),

)
